name: CICD

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/springbootexampleforgithubaction .
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/springbootexampleforgithubaction:latest

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Install Docker
        run: |
          if ! command -v docker &> /dev/null; then
              sudo apt-get update
              sudo apt-get install -y docker.io
              sudo usermod -aG docker $(whoami)
              sudo systemctl restart docker
          fi
      - name: Pull Image From DockerHub
        run: docker pull ragul05/springbootexampleforgithubaction:latest
      - name: Delete Old Container
        run: docker rm -f springboot-example-container || true
      - name: Run Docker Container
        run: docker run -d -p 8080:8080 --name springboot-example-container ${{ secrets.DOCKERHUB_USERNAME }}/springbootexampleforgithubaction:latest

